
# SEO settings
title: "redfast00 "
title2: "blog"
description: "A security and programming blog"
keywords: "Android, hacking, reverse engineering, linux"
url: https://redfast00.github.io
baseurl: null

repo: http://github.com/heiswayi/thinkspace
twitter_username: "redfast00"

# Build settings
permalink: /:year-:title.html
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "redfast00"
  job      : "Programmer/Hacker"
  bio      : ""
  thumb    : /images/author.jpg
  email    : redfast00@gmail.com
  url      : https://redfast00.github.io
  github   : https://github.com/redfast00
  twitter  : http://twitter.com/redfast00
  facebook : none
  linkedin : none

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@redfast00"

gems:
  - bourbon
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog
